[package]
name = "chiave-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
zeroize.workspace = true
secrecy.workspace = true
keepass = { version = "0.13", features = ["save_kdbx4", "totp"] }
